### ISSUE TITLE
New release with new name?

### ISSUE THREAD

**Issue by reedy** [php-parallel-lint/PHP-Console-Color#1]
Can you tag a new release that uses the packages from the php-parallel-lint organization/vendor? Thanks!

Same as https://github.com/php-parallel-lint/PHP-Console-Highlighter/issues/1

**Comment by grogy** [comment]
I will do it. Last think for it is add changelog like https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/master/CHANGELOG.md

**Comment by grogy** [comment]
Can you add changelog and send PR for faster creation new release? :-)

**Comment by reedy** [comment]
> Can you add changelog and send PR for faster creation new release? :-)

It took less than 10 minutes...

**Comment by reedy** [comment]
> Can you add changelog and send PR for faster creation new release? :-)

And 12 days later... It's not been merged anyway...

**Comment by grogy** [comment]
Released new version https://github.com/php-parallel-lint/PHP-Console-Color/releases/tag/v0.3
