### ISSUE TITLE
Switch to using GH Actions

### ISSUE THREAD

**Issue by jrfnl** [php-parallel-lint/PHP-Console-Color#15]
As Travis for open source has died a quiet dead, I propose switching the CI building over to GH Actions.
While we're at it, we may as well get rid of Ant as well.

I have made preparations to action this. and PR #13 and #14 are preliminary PRs before pulling the PR to switch the CI over.

**Comment by jrfnl** [comment]
PR #16 is another prelim PR. Once that has been merged, I can pull the GH Actions PR.

**Comment by grogy** [comment]
PR #16 merged ;)

**Comment by jrfnl** [comment]
And the CI switch over PR has now been pulled ;-)

**Comment by grogy** [comment]
You are fast! Give me a moment.. :-))

**Comment by grogy** [comment]
Thank you, it looks very good :))

**Comment by jrfnl** [comment]
> You are fast! Give me a moment.. :-))

*grin* Well, I had the commits ready locally, all I needed to do was rebase & run a final test with it. (see the commit date)
