### ISSUE TITLE
Add support for Coveralls.io

### ISSUE THREAD

**Issue by grogy** [php-parallel-lint/PHP-Console-Color#29]

**Comment by jrfnl** [comment]
I'd be happy to set up the CI side of this, but to do so, an account needs to be created and the Coveralls service needs Oauth permission for this organisation.

**Comment by grogy** [comment]
I will do it. I want prepare some change-set too, you make too much :-) I will learn something new with Coveralls.

**Comment by jrfnl** [comment]
In that case, let me leave this here for inspiration:

https://github.com/PHPCompatibility/PHPCompatibility/blob/8c49d1cb405b6e2fd8e627641cd48b00764960e1/.github/workflows/test.yml#L309-L341

**Comment by grogy** [comment]
It's done
